# Generated by Django 2.1.5 on 2019-02-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20190207_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nearby',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='nearby',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='nearby',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nearby',
            old_name='Type',
            new_name='place_type',
        ),
    ]
